version: '3'
services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./form_data.db:/form_data.db
    expose:
      - "5001"
    environment:
      FLASK_ENV: production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/html/index.html:/var/www/html/index.html
      - /etc/nginx/sites-available/default:/etc/nginx/conf.d/default.conf
      - /etc/certs:/etc/certs:ro
    depends_on:
      - flaskapp

volumes:
  db_data:

